package dao;

import java.sql.*; import java.util.*; import model.Responsavel;
public class ResponsavelDAO {
    private static final String CHAVE_AES="chave_saep_2026";
    public boolean inserir(Responsavel r){String sql="INSERT INTO responsavel (nome,cpf,telefone,email) VALUES (?,AES_ENCRYPT(?,?),?,?)";try(Connection c=Conexao.conectar();PreparedStatement s=c.prepareStatement(sql)){s.setString(1,r.getNome());s.setString(2,r.getCpf());s.setString(3,CHAVE_AES);s.setString(4,r.getTelefone());s.setString(5,r.getEmail());return s.executeUpdate()>0;}catch(Exception e){System.out.println("Erro ao inserir responsável: "+e.getMessage());return false;}}
    public boolean atualizar(Responsavel r){String sql="UPDATE responsavel SET nome=?,cpf=AES_ENCRYPT(?,?),telefone=?,email=? WHERE id=?";try(Connection c=Conexao.conectar();PreparedStatement s=c.prepareStatement(sql)){s.setString(1,r.getNome());s.setString(2,r.getCpf());s.setString(3,CHAVE_AES);s.setString(4,r.getTelefone());s.setString(5,r.getEmail());s.setInt(6,r.getId());return s.executeUpdate()>0;}catch(Exception e){System.out.println("Erro ao atualizar responsável: "+e.getMessage());return false;}}
    public boolean excluir(int id){try(Connection c=Conexao.conectar();PreparedStatement s=c.prepareStatement("DELETE FROM responsavel WHERE id=?")){s.setInt(1,id);return s.executeUpdate()>0;}catch(Exception e){System.out.println("Erro ao excluir responsável: "+e.getMessage());return false;}}
    public List<Responsavel> listar(String termo){List<Responsavel> l=new ArrayList<>();String sql="SELECT id,nome,CAST(AES_DECRYPT(cpf,?) AS CHAR) cpf,telefone,email FROM responsavel WHERE nome LIKE ? OR telefone LIKE ? OR email LIKE ? OR CAST(AES_DECRYPT(cpf,?) AS CHAR) LIKE ? ORDER BY nome";try(Connection c=Conexao.conectar();PreparedStatement s=c.prepareStatement(sql)){String b="%"+termo+"%";s.setString(1,CHAVE_AES);s.setString(2,b);s.setString(3,b);s.setString(4,b);s.setString(5,CHAVE_AES);s.setString(6,b);try(ResultSet rs=s.executeQuery()){while(rs.next()){Responsavel r=new Responsavel();r.setId(rs.getInt("id"));r.setNome(rs.getString("nome"));r.setCpf(rs.getString("cpf"));r.setTelefone(rs.getString("telefone"));r.setEmail(rs.getString("email"));l.add(r);}}}catch(Exception e){System.out.println("Erro ao listar responsáveis: "+e.getMessage());}return l;}
    public List<Responsavel> listarTodos(){return listar("");}
}