package view;
import dao.*; import java.awt.*; import javax.swing.*; import javax.swing.table.DefaultTableModel; import model.*;
public class TelaDependente extends JFrame { private final JTextField nome=new JTextField(),nasc=new JTextField(),alergias=new JTextField();private final JComboBox<String> sexo=new JComboBox<>(new String[]{"Feminino","Masculino","Outro"});private final JComboBox<Responsavel> resp=new JComboBox<>();private final DependenteDAO dao=new DependenteDAO();private final ResponsavelDAO rdao=new ResponsavelDAO();private int id=0;private final DefaultTableModel m=new DefaultTableModel(new Object[]{"ID","Nome","Nascimento","Sexo","Alergias","Responsável"},0){public boolean isCellEditable(int r,int c){return false;}};private final JTable tabela=new JTable(m);
 public TelaDependente(){mascara(nasc,"DATA");setTitle("Dependentes");setDefaultCloseOperation(DISPOSE_ON_CLOSE);setSize(950,560);setLocationRelativeTo(null);JPanel c=new JPanel(new GridLayout(5,2,8,8));c.add(new JLabel("Nome:"));c.add(nome);c.add(new JLabel("Nascimento (DD/MM/AAAA):"));c.add(nasc);c.add(new JLabel("Sexo:"));c.add(sexo);c.add(new JLabel("Alergias/Observações:"));c.add(alergias);c.add(new JLabel("Responsável:"));c.add(resp);JButton s=new JButton("Salvar"),a=new JButton("Atualizar"),e=new JButton("Excluir"),l=new JButton("Novo/Limpar");JPanel b=new JPanel();for(JButton x:new JButton[]{s,a,e,l})b.add(x);JPanel top=new JPanel(new BorderLayout());top.setBorder(BorderFactory.createEmptyBorder(10,10,10,10));top.add(c);top.add(b,BorderLayout.SOUTH);add(top,BorderLayout.NORTH);add(new JScrollPane(tabela));s.addActionListener(x->salvar());a.addActionListener(x->atualizar());e.addActionListener(x->excluir());l.addActionListener(x->limpar());tabela.getSelectionModel().addListSelectionListener(x->{if(!x.getValueIsAdjusting())selecionar();});for(Responsavel r:rdao.listarTodos())resp.addItem(r);carregar();}
 private final java.time.format.DateTimeFormatter fd=java.time.format.DateTimeFormatter.ofPattern("dd/MM/uuuu").withResolverStyle(java.time.format.ResolverStyle.STRICT); private java.sql.Date sqlDate(String s){return java.sql.Date.valueOf(java.time.LocalDate.parse(s,fd));} private String data(java.sql.Date d){return d==null?"":d.toLocalDate().format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy"));}
 private boolean validar(){try{if(nome.getText().trim().isEmpty()||resp.getSelectedItem()==null)throw new Exception();sqlDate(nasc.getText());return true;}catch(Exception e){JOptionPane.showMessageDialog(this,"Informe nome, data válida (DD/MM/AAAA) e responsável.");return false;}} private Dependente obj(){Dependente d=new Dependente();d.setId(id);d.setNome(nome.getText().trim());d.setDataNascimento(sqlDate(nasc.getText()));d.setSexo(String.valueOf(sexo.getSelectedItem()));d.setAlergias(alergias.getText().trim());d.setResponsavelId(((Responsavel)resp.getSelectedItem()).getId());return d;} private void salvar(){if(validar()&&dao.inserir(obj())){JOptionPane.showMessageDialog(this,"Dependente cadastrado.");limpar();carregar();}}private void atualizar(){if(id==0)return;if(validar()&&dao.atualizar(obj())){limpar();carregar();}}private void excluir(){if(id==0)return;if(JOptionPane.showConfirmDialog(this,"Excluir dependente?","Confirmação",0)==0){if(dao.excluir(id)){limpar();carregar();}else JOptionPane.showMessageDialog(this,"Não foi possível excluir. Verifique as consultas associadas.");}}private void carregar(){m.setRowCount(0);for(Dependente d:dao.listarTodos())m.addRow(new Object[]{d.getId(),d.getNome(),data(d.getDataNascimento()),d.getSexo(),d.getAlergias(),d.getNomeResponsavel()});}private void selecionar(){int r=tabela.getSelectedRow();if(r<0)return;int x=(int)m.getValueAt(r,0);for(Dependente d:dao.listarTodos())if(d.getId()==x){id=x;nome.setText(d.getNome());nasc.setText(data(d.getDataNascimento()));sexo.setSelectedItem(d.getSexo());alergias.setText(d.getAlergias());for(int i=0;i<resp.getItemCount();i++)if(resp.getItemAt(i).getId()==d.getResponsavelId())resp.setSelectedIndex(i);break;}}private void limpar(){id=0;nome.setText("");nasc.setText("");alergias.setText("");tabela.clearSelection();}

    private static class MascaraDinamicaFilter extends javax.swing.text.DocumentFilter {
        private final String tipo; MascaraDinamicaFilter(String tipo){this.tipo=tipo;}
        public void insertString(FilterBypass fb,int o,String s,javax.swing.text.AttributeSet a)throws javax.swing.text.BadLocationException{trocar(fb,o,0,s,a);}
        public void replace(FilterBypass fb,int o,int l,String s,javax.swing.text.AttributeSet a)throws javax.swing.text.BadLocationException{trocar(fb,o,l,s,a);}
        public void remove(FilterBypass fb,int o,int l)throws javax.swing.text.BadLocationException{trocar(fb,o,l,"",null);}
        private void trocar(FilterBypass fb,int o,int l,String t,javax.swing.text.AttributeSet a)throws javax.swing.text.BadLocationException{javax.swing.text.Document d=fb.getDocument();String x=d.getText(0,d.getLength());String n=(x.substring(0,o)+(t==null?"":t)+x.substring(o+l)).replaceAll("\\D","");int m=tipo.equals("CPF")||tipo.equals("TEL")?11:tipo.equals("DATA")?8:4;if(n.length()>m)n=n.substring(0,m);String f=n;if(tipo.equals("CPF")){if(n.length()>9)f=n.substring(0,3)+"."+n.substring(3,6)+"."+n.substring(6,9)+"-"+n.substring(9);else if(n.length()>6)f=n.substring(0,3)+"."+n.substring(3,6)+"."+n.substring(6);else if(n.length()>3)f=n.substring(0,3)+"."+n.substring(3);}else if(tipo.equals("TEL")){if(n.length()>7)f="("+n.substring(0,2)+")"+n.substring(2,7)+"-"+n.substring(7);else if(n.length()>2)f="("+n.substring(0,2)+")"+n.substring(2);else if(!n.isEmpty())f="("+n;}else if(tipo.equals("DATA")){if(n.length()>4)f=n.substring(0,2)+"/"+n.substring(2,4)+"/"+n.substring(4);else if(n.length()>2)f=n.substring(0,2)+"/"+n.substring(2);}else if(tipo.equals("HORA")&&n.length()>2)f=n.substring(0,2)+":"+n.substring(2);fb.replace(0,d.getLength(),f,a);}
    }
    private void mascara(javax.swing.JTextField c,String t){((javax.swing.text.AbstractDocument)c.getDocument()).setDocumentFilter(new MascaraDinamicaFilter(t));}
}