package view;
import dao.*;import java.awt.*;import javax.swing.*;import javax.swing.table.DefaultTableModel;import model.*;
public class TelaConsulta extends JFrame {private final JComboBox<Dependente> dep=new JComboBox<>();private final JTextField data=new JTextField(),hora=new JTextField(),motivo=new JTextField();private final ConsultaDAO dao=new ConsultaDAO();private final DependenteDAO ddao=new DependenteDAO();private int id=0;private final DefaultTableModel m=new DefaultTableModel(new Object[]{"ID","Data","Hora","Dependente","Nascimento","Sexo","Alergias","Responsável","CPF","Telefone","E-mail","Motivo"},0){public boolean isCellEditable(int r,int c){return false;}};private final JTable tabela=new JTable(m);private final java.time.format.DateTimeFormatter fd=java.time.format.DateTimeFormatter.ofPattern("dd/MM/uuuu").withResolverStyle(java.time.format.ResolverStyle.STRICT),fh=java.time.format.DateTimeFormatter.ofPattern("HH:mm").withResolverStyle(java.time.format.ResolverStyle.STRICT);
 public TelaConsulta(){mascara(data,"DATA");mascara(hora,"HORA");setTitle("Consultas Pediátricas");setDefaultCloseOperation(DISPOSE_ON_CLOSE);setSize(1250,620);setLocationRelativeTo(null);JPanel c=new JPanel(new GridLayout(4,2,8,8));c.add(new JLabel("Dependente:"));c.add(dep);c.add(new JLabel("Data (DD/MM/AAAA):"));c.add(data);c.add(new JLabel("Horário (HH:MM):"));c.add(hora);c.add(new JLabel("Motivo da consulta:"));c.add(motivo);JButton s=new JButton("Salvar"),a=new JButton("Atualizar"),e=new JButton("Excluir"),l=new JButton("Novo/Limpar");JPanel b=new JPanel();for(JButton x:new JButton[]{s,a,e,l})b.add(x);JPanel top=new JPanel(new BorderLayout());top.setBorder(BorderFactory.createEmptyBorder(10,10,10,10));top.add(c);top.add(b,BorderLayout.SOUTH);add(top,BorderLayout.NORTH);add(new JScrollPane(tabela));for(Dependente d:ddao.listarTodos())dep.addItem(d);s.addActionListener(x->salvar());a.addActionListener(x->atualizar());e.addActionListener(x->excluir());l.addActionListener(x->limpar());tabela.getSelectionModel().addListSelectionListener(x->{if(!x.getValueIsAdjusting())selecionar();});carregar();}
 private java.sql.Date sd(String s){return java.sql.Date.valueOf(java.time.LocalDate.parse(s,fd));}private java.sql.Time st(String s){return java.sql.Time.valueOf(java.time.LocalTime.parse(s,fh));}private String d(java.sql.Date x){return x==null?"":x.toLocalDate().format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy"));}private String h(java.sql.Time x){return x==null?"":x.toLocalTime().format(java.time.format.DateTimeFormatter.ofPattern("HH:mm"));}private String nums(String s){return s==null?"":s.replaceAll("\\D","");}private String cpf(String s){String n=nums(s);return n.length()==11?n.substring(0,3)+"."+n.substring(3,6)+"."+n.substring(6,9)+"-"+n.substring(9):s;}private String tel(String s){String n=nums(s);return n.length()==11?"("+n.substring(0,2)+")"+n.substring(2,7)+"-"+n.substring(7):s;}
 private boolean validar(){try{if(dep.getSelectedItem()==null)throw new Exception();sd(data.getText());st(hora.getText());return true;}catch(Exception e){JOptionPane.showMessageDialog(this,"Informe dependente, data e horário válidos.");return false;}}private Consulta obj(){Consulta c=new Consulta();c.setId(id);c.setDependenteId(((Dependente)dep.getSelectedItem()).getId());c.setDataConsulta(sd(data.getText()));c.setHorario(st(hora.getText()));c.setMotivo(motivo.getText().trim());return c;}private void salvar(){if(validar()&&dao.inserir(obj())){JOptionPane.showMessageDialog(this,"Consulta cadastrada.");limpar();carregar();}}private void atualizar(){if(id==0)return;if(validar()&&dao.atualizar(obj())){limpar();carregar();}}private void excluir(){if(id>0&&JOptionPane.showConfirmDialog(this,"Excluir consulta?","Confirmação",0)==0&&dao.excluir(id)){limpar();carregar();}}private void carregar(){m.setRowCount(0);for(Consulta c:dao.listarTodos())m.addRow(new Object[]{c.getId(),d(c.getDataConsulta()),h(c.getHorario()),c.getNomeDependente(),d(c.getNascimentoDependente()),c.getSexoDependente(),c.getAlergiasDependente(),c.getNomeResponsavel(),cpf(c.getCpfResponsavel()),tel(c.getTelefoneResponsavel()),c.getEmailResponsavel(),c.getMotivo()});}private void selecionar(){int r=tabela.getSelectedRow();if(r<0)return;int x=(int)m.getValueAt(r,0);for(Consulta c:dao.listarTodos())if(c.getId()==x){id=x;data.setText(d(c.getDataConsulta()));hora.setText(h(c.getHorario()));motivo.setText(c.getMotivo());for(int i=0;i<dep.getItemCount();i++)if(dep.getItemAt(i).getId()==c.getDependenteId())dep.setSelectedIndex(i);break;}}private void limpar(){id=0;data.setText("");hora.setText("");motivo.setText("");tabela.clearSelection();}

    private static class MascaraDinamicaFilter extends javax.swing.text.DocumentFilter {
        private final String tipo; MascaraDinamicaFilter(String tipo){this.tipo=tipo;}
        public void insertString(FilterBypass fb,int o,String s,javax.swing.text.AttributeSet a)throws javax.swing.text.BadLocationException{trocar(fb,o,0,s,a);}
        public void replace(FilterBypass fb,int o,int l,String s,javax.swing.text.AttributeSet a)throws javax.swing.text.BadLocationException{trocar(fb,o,l,s,a);}
        public void remove(FilterBypass fb,int o,int l)throws javax.swing.text.BadLocationException{trocar(fb,o,l,"",null);}
        private void trocar(FilterBypass fb,int o,int l,String t,javax.swing.text.AttributeSet a)throws javax.swing.text.BadLocationException{javax.swing.text.Document d=fb.getDocument();String x=d.getText(0,d.getLength());String n=(x.substring(0,o)+(t==null?"":t)+x.substring(o+l)).replaceAll("\\D","");int m=tipo.equals("CPF")||tipo.equals("TEL")?11:tipo.equals("DATA")?8:4;if(n.length()>m)n=n.substring(0,m);String f=n;if(tipo.equals("CPF")){if(n.length()>9)f=n.substring(0,3)+"."+n.substring(3,6)+"."+n.substring(6,9)+"-"+n.substring(9);else if(n.length()>6)f=n.substring(0,3)+"."+n.substring(3,6)+"."+n.substring(6);else if(n.length()>3)f=n.substring(0,3)+"."+n.substring(3);}else if(tipo.equals("TEL")){if(n.length()>7)f="("+n.substring(0,2)+")"+n.substring(2,7)+"-"+n.substring(7);else if(n.length()>2)f="("+n.substring(0,2)+")"+n.substring(2);else if(!n.isEmpty())f="("+n;}else if(tipo.equals("DATA")){if(n.length()>4)f=n.substring(0,2)+"/"+n.substring(2,4)+"/"+n.substring(4);else if(n.length()>2)f=n.substring(0,2)+"/"+n.substring(2);}else if(tipo.equals("HORA")&&n.length()>2)f=n.substring(0,2)+":"+n.substring(2);fb.replace(0,d.getLength(),f,a);}
    }
    private void mascara(javax.swing.JTextField c,String t){((javax.swing.text.AbstractDocument)c.getDocument()).setDocumentFilter(new MascaraDinamicaFilter(t));}
}