package view;
import dao.ResponsavelDAO; import java.awt.*; import java.util.*; import javax.swing.*; import javax.swing.event.*; import javax.swing.table.DefaultTableModel; import model.Responsavel;
public class TelaResponsavel extends JFrame {
 private final JTextField nome=new JTextField(),cpf=new JTextField(),tel=new JTextField(),email=new JTextField(),pesquisa=new JTextField(); private final ResponsavelDAO dao=new ResponsavelDAO(); private int id=0;
 private final DefaultTableModel m=new DefaultTableModel(new Object[]{"ID","Nome","CPF","Telefone","E-mail"},0){public boolean isCellEditable(int r,int c){return false;}}; private final JTable tabela=new JTable(m);
 public TelaResponsavel(){mascara(cpf,"CPF");mascara(tel,"TEL");setTitle("Responsáveis");setDefaultCloseOperation(DISPOSE_ON_CLOSE);setSize(900,560);setLocationRelativeTo(null);JPanel c=new JPanel(new GridLayout(4,2,8,8));c.add(new JLabel("Nome:"));c.add(nome);c.add(new JLabel("CPF:"));c.add(cpf);c.add(new JLabel("Telefone:"));c.add(tel);c.add(new JLabel("E-mail:"));c.add(email);JButton s=new JButton("Salvar"),a=new JButton("Atualizar"),e=new JButton("Excluir"),l=new JButton("Novo/Limpar");JPanel b=new JPanel();for(JButton x:new JButton[]{s,a,e,l})b.add(x);JPanel top=new JPanel(new BorderLayout(8,8));top.setBorder(BorderFactory.createEmptyBorder(10,10,10,10));top.add(c,BorderLayout.CENTER);top.add(b,BorderLayout.SOUTH);JPanel p=new JPanel(new BorderLayout(8,8));p.setBorder(BorderFactory.createEmptyBorder(0,10,10,10));p.add(new JLabel("Pesquisar:"),BorderLayout.WEST);p.add(pesquisa);JPanel n=new JPanel(new BorderLayout());n.add(top,BorderLayout.NORTH);n.add(p,BorderLayout.SOUTH);add(n,BorderLayout.NORTH);add(new JScrollPane(tabela));s.addActionListener(x->salvar());a.addActionListener(x->atualizar());e.addActionListener(x->excluir());l.addActionListener(x->limpar());tabela.getSelectionModel().addListSelectionListener(x->{if(!x.getValueIsAdjusting())selecionar();});pesquisa.getDocument().addDocumentListener(new DocumentListener(){public void insertUpdate(DocumentEvent e){carregar();}public void removeUpdate(DocumentEvent e){carregar();}public void changedUpdate(DocumentEvent e){carregar();}});carregar();}
 private String nums(String s){return s==null?"":s.replaceAll("\\D","");} private String fcpf(String s){String n=nums(s);return n.length()==11?n.substring(0,3)+"."+n.substring(3,6)+"."+n.substring(6,9)+"-"+n.substring(9):s;} private String ftel(String s){String n=nums(s);return n.length()==11?"("+n.substring(0,2)+")"+n.substring(2,7)+"-"+n.substring(7):s;}
 private Responsavel obj(){Responsavel r=new Responsavel();r.setId(id);r.setNome(nome.getText().trim());r.setCpf(nums(cpf.getText()));r.setTelefone(nums(tel.getText()));r.setEmail(email.getText().trim());return r;} private boolean validar(){if(nome.getText().trim().isEmpty()||nums(cpf.getText()).length()!=11){JOptionPane.showMessageDialog(this,"Informe nome e CPF com 11 dígitos.");return false;}return true;}
 private void salvar(){if(validar()&&dao.inserir(obj())){JOptionPane.showMessageDialog(this,"Responsável cadastrado.");limpar();carregar();}} private void atualizar(){if(id==0){JOptionPane.showMessageDialog(this,"Selecione um responsável.");return;}if(validar()&&dao.atualizar(obj())){JOptionPane.showMessageDialog(this,"Responsável atualizado.");limpar();carregar();}} private void excluir(){if(id==0)return;if(JOptionPane.showConfirmDialog(this,"Excluir responsável?","Confirmação",JOptionPane.YES_NO_OPTION)==0){if(dao.excluir(id)){limpar();carregar();}else JOptionPane.showMessageDialog(this,"Não foi possível excluir. Verifique os dependentes associados.");}}
 private void selecionar(){int r=tabela.getSelectedRow();if(r<0)return;id=(int)m.getValueAt(r,0);nome.setText(String.valueOf(m.getValueAt(r,1)));cpf.setText(String.valueOf(m.getValueAt(r,2)));tel.setText(String.valueOf(m.getValueAt(r,3)));email.setText(String.valueOf(m.getValueAt(r,4)));} private void limpar(){id=0;nome.setText("");cpf.setText("");tel.setText("");email.setText("");tabela.clearSelection();} private void carregar(){m.setRowCount(0);for(Responsavel r:dao.listar(pesquisa.getText().trim()))m.addRow(new Object[]{r.getId(),r.getNome(),fcpf(r.getCpf()),ftel(r.getTelefone()),r.getEmail()});}

    private static class MascaraDinamicaFilter extends javax.swing.text.DocumentFilter {
        private final String tipo; MascaraDinamicaFilter(String tipo){this.tipo=tipo;}
        public void insertString(FilterBypass fb,int o,String s,javax.swing.text.AttributeSet a)throws javax.swing.text.BadLocationException{trocar(fb,o,0,s,a);}
        public void replace(FilterBypass fb,int o,int l,String s,javax.swing.text.AttributeSet a)throws javax.swing.text.BadLocationException{trocar(fb,o,l,s,a);}
        public void remove(FilterBypass fb,int o,int l)throws javax.swing.text.BadLocationException{trocar(fb,o,l,"",null);}
        private void trocar(FilterBypass fb,int o,int l,String t,javax.swing.text.AttributeSet a)throws javax.swing.text.BadLocationException{javax.swing.text.Document d=fb.getDocument();String x=d.getText(0,d.getLength());String n=(x.substring(0,o)+(t==null?"":t)+x.substring(o+l)).replaceAll("\\D","");int m=tipo.equals("CPF")||tipo.equals("TEL")?11:tipo.equals("DATA")?8:4;if(n.length()>m)n=n.substring(0,m);String f=n;if(tipo.equals("CPF")){if(n.length()>9)f=n.substring(0,3)+"."+n.substring(3,6)+"."+n.substring(6,9)+"-"+n.substring(9);else if(n.length()>6)f=n.substring(0,3)+"."+n.substring(3,6)+"."+n.substring(6);else if(n.length()>3)f=n.substring(0,3)+"."+n.substring(3);}else if(tipo.equals("TEL")){if(n.length()>7)f="("+n.substring(0,2)+")"+n.substring(2,7)+"-"+n.substring(7);else if(n.length()>2)f="("+n.substring(0,2)+")"+n.substring(2);else if(!n.isEmpty())f="("+n;}else if(tipo.equals("DATA")){if(n.length()>4)f=n.substring(0,2)+"/"+n.substring(2,4)+"/"+n.substring(4);else if(n.length()>2)f=n.substring(0,2)+"/"+n.substring(2);}else if(tipo.equals("HORA")&&n.length()>2)f=n.substring(0,2)+":"+n.substring(2);fb.replace(0,d.getLength(),f,a);}
    }
    private void mascara(javax.swing.JTextField c,String t){((javax.swing.text.AbstractDocument)c.getDocument()).setDocumentFilter(new MascaraDinamicaFilter(t));}
}